defmodule OpsBrainWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ops_brain

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ops_brain_key",
    signing_salt: "1rqpfYiU",
    encryption_salt: "operator-session-v1",
    http_only: true,
    secure: Application.compile_env(:ops_brain, :secure_cookies, false),
    same_site: "Strict",
    max_age: 28_800
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ops_brain,
    gzip: not code_reloading?,
    only: OpsBrainWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ops_brain, skip_table_creation: true
  end

  plug Plug.Static, at: "/vendor/phoenix", from: {:phoenix, "priv/static"}, only: ["phoenix.js"]

  plug Plug.Static,
    at: "/vendor/live_view",
    from: {:phoenix_live_view, "priv/static"},
    only: ["phoenix_live_view.js"]

  plug Plug.Static,
    at: "/vendor/html",
    from: {:phoenix_html, "priv/static"},
    only: ["phoenix_html.js"]

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 16_384,
    read_length: 16_384

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OpsBrainWeb.Router
end
